### ISSUE TITLE
Outsource attribute :ClinicalTrial{leadSponsorName|collaboratorName} to seperate node

### ISSUE THREAD

**Issue by motey** [covidgraph/data_clinical-trials-gov#1]
Sebastian:  I thought that maybe Lead Sponsors and Collaborators should become their own Entity nodes. Unless they are never the same, of course. Right now they are simple attributes, but it might be interesting to see what other trials a sponsor had been sponsoring or what other collaborators where doing

Tim: i guess there are some overlaps with :Affilition and :Entity nodes [with leadSponsorName].
later possible nlp entity linking and the resulting node merging would be straightforward when having seperated nodes

**Task**

Change https://github.com/covidgraph/data_clinical-trials-gov/blob/master/dataloader/load_data.cypher to have a new node for each `leadSponsorName`and `collaboratorName` which is a property of :ClinicalTrial atm. Of course create a relationship to the source :ClinicalTrial node as well

**Comment by KirstenLangendorf** [comment]
Has been implemented in release 0.1.1 and 0.2
